version: 2.1
jobs:
  # Job to build and test the application
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install --save
      # Add steps here to build and test the application
  
  # Job to build and push Docker image
  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      # Set up remote Docker
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            docker build -t nodejswebapp1 -t nitishmalang/nodejswebapp1:latest .
            echo $DOCKER_PASSWORD | docker login -u nitishmalang --password-stdin
            docker push nitishmalang/nodejswebapp1:latest

workflows:
  build_test_and_push_image:
    jobs:
      - build_test
      - build_docker_image
