version: 2.1

jobs:
  build_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t nodejswebapp1 -t nitishmalang/nodejswebapp1:latest .
            echo $DOCKER_PASSWORD | docker login -u nitishmalang --password-stdin
            docker push nitishmalang/nodejswebapp1:latest

workflows:
  build_test:
    jobs:
      - build_tests
      - build_docker_image:
          filters:
            branches:
              only: develop-circleci
