version: 2.1

jobs:
  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t nodejswebapp1 -t nitishmalang/nodejswebapp1:latest .

workflows:
  build:
    jobs:
      - build_docker_image:
          filters:
            branches:
              only: develop-circleci

